language: python

python:
  - "2.7"
#  - "3.3"
  - "3.4"

# install: "pip install -e . behave"

# script: "cd test/ && behave"

branches:
  only:
  - recipy_test

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
# Install test framework packages.
# Install py.test explicitly else travis virtualenv one is used 
# which can't use the miniconda environment.
  - conda install pytest python-dateutil pyyaml numpy
# conda can't find gitpython so pip install.
  - pip install gitpython
# setup.py fails to install flask for as-yet-unknown reason.
  - conda install flask
# Install packages for testing recipy.
  - conda install matplotlib
  - conda install pandas pytables xlrd xlwt
  - conda install lxml
  - conda install beautifulsoup4
  - conda install pillow
  - conda install scikit-learn
  - conda install scikit-image
  - pip install nibabel
  - conda install gdal
# Install recipy.
  - python setup.py install
  - which python
  - which pip
  - which py.test
  - py.test --version
  - pip freeze

script:
# Copy matplotlib configuration so it does not try and plot to
# screen. 
  - cp integration_test/packages/matplotlibrc .
# Run py.test with 'v' (verbose) to show test function names and 
# 'rs' to show reasons for skipped tests
  - py.test -v -rs integration_test
